const ISO3List = {
    'Afghanistan': {numeric: 4, alpha3: 'AFG', name: 'Afghanistan'},
    'Albania': {numeric: 8, alpha3: 'ALB', name: 'Albania'},
    'Algeria': {numeric: 12, alpha3: 'DZA', name: 'Algeria'},
    'American Samoa': {numeric: 16, alpha3: 'ASM', name: 'American,Samoa'},
    'Andorra': {numeric: 20, alpha3: 'AND', name: 'Andorra'},
    'Angola': {numeric: 24, alpha3: 'AGO', name: 'Angola'},
    'Anguilla': {numeric: 660, alpha3: 'AIA', name: 'Anguilla'},
    'Antarctica': {numeric: 10, alpha3: 'ATA', name: 'Antarctica'},
    'Antigua and Barbuda': {numeric: 28, alpha3: 'ATG', name: 'Antigua,and,Barbuda'},
    'Argentina': {numeric: 32, alpha3: 'ARG', name: 'Argentina'},
    'Armenia': {numeric: 51, alpha3: 'ARM', name: 'Armenia'},
    'Aruba': {numeric: 533, alpha3: 'ABW', name: 'Aruba'},
    'Australia': {numeric: 36, alpha3: 'AUS', name: 'Australia'},
    'Austria': {numeric: 40, alpha3: 'AUT', name: 'Austria'},
    'Azerbaijan': {numeric: 31, alpha3: 'AZE', name: 'Azerbaijan'},
    'Bahamas': {numeric: 44, alpha3: 'BHS', name: 'Bahamas'},
    'Bahrain': {numeric: 48, alpha3: 'BHR', name: 'Bahrain'},
    'Bangladesh': {numeric: 50, alpha3: 'BGD', name: 'Bangladesh'},
    'Barbados': {numeric: 52, alpha3: 'BRB', name: 'Barbados'},
    'Belarus': {numeric: 112, alpha3: 'BLR', name: 'Belarus'},
    'Belgium': {numeric: 56, alpha3: 'BEL', name: 'Belgium'},
    'Belize': {numeric: 84, alpha3: 'BLZ', name: 'Belize'},
    'Benin': {numeric: 204, alpha3: 'BEN', name: 'Benin'},
    'Bermuda': {numeric: 60, alpha3: 'BMU', name: 'Bermuda'},
    'Bhutan': {numeric: 64, alpha3: 'BTN', name: 'Bhutan'},
    'Bolivia': {numeric: 68, alpha3: 'BOL', name: 'Bolivia,,Plurinational,State,of'},
    'Caribbean Netherlands': {numeric: 535, alpha3: 'BES', name: 'Bonaire,,Sint,Eustatius,and,Saba'},
    'Bosnia and Herzegovina': {numeric: 70, alpha3: 'BIH', name: 'Bosnia,and,Herzegovina'},
    'Botswana': {numeric: 72, alpha3: 'BWA', name: 'Botswana'},
    'Bouvet Island': {numeric: 74, alpha3: 'BVT', name: 'Bouvet,Island'},
    'Brazil': {numeric: 76, alpha3: 'BRA', name: 'Brazil'},
    'British,Indian,Ocean,Territory': {numeric: 86, alpha3: 'IOT', name: 'British,Indian,Ocean,Territory'},
    'Brunei': {numeric: 96, alpha3: 'BRN', name: 'Brunei,Darussalam'},
    'Bulgaria': {numeric: 100, alpha3: 'BGR', name: 'Bulgaria'},
    'Burkina Faso': {numeric: 854, alpha3: 'BFA', name: 'Burkina,Faso'},
    'Burundi': {numeric: 108, alpha3: 'BDI', name: 'Burundi'},
    'Cambodia': {numeric: 116, alpha3: 'KHM', name: 'Cambodia'},
    'Cameroon': {numeric: 120, alpha3: 'CMR', name: 'Cameroon'},
    'Canada': {numeric: 124, alpha3: 'CAN', name: 'Canada'},
    'Cabo Verde': {numeric: 132, alpha3: 'CPV', name: 'Cape,Verde'},
    'Cayman Islands': {numeric: 136, alpha3: 'CYM', name: 'Cayman,Islands'},
    'Central African Republic': {numeric: 140, alpha3: 'CAF', name: 'Central,African,Republic'},
    'Chad': {numeric: 148, alpha3: 'TCD', name: 'Chad'},
    'Chile': {numeric: 152, alpha3: 'CHL', name: 'Chile'},
    'China': {numeric: 156, alpha3: 'CHN', name: 'China'},
    'Christmas,Island': {numeric: 162, alpha3: 'CXR', name: 'Christmas,Island'},
    'Cocos,(Keeling),Islands': {numeric: 166, alpha3: 'CCK', name: 'Cocos,(Keeling),Islands'},
    'Colombia': {numeric: 170, alpha3: 'COL', name: 'Colombia'},
    'Comoros': {numeric: 174, alpha3: 'COM', name: 'Comoros'},
    'Congo': {numeric: 178, alpha3: 'COG', name: 'Congo'},
    'DR Congo': {numeric: 180, alpha3: 'COD', name: 'Congo,,the,Democratic,Republic,of,the'},
    'Cook Islands': {numeric: 184, alpha3: 'COK', name: 'Cook,Islands'},
    'Costa Rica': {numeric: 188, alpha3: 'CRI', name: 'Costa,Rica'},
    'Croatia': {numeric: 191, alpha3: 'HRV', name: 'Croatia'},
    'Cuba': {numeric: 192, alpha3: 'CUB', name: 'Cuba'},
    'Curaçao': {numeric: 531, alpha3: 'CUW', name: 'Curaçao'},
    'Cyprus': {numeric: 196, alpha3: 'CYP', name: 'Cyprus'},
    'Czech Republic (Czechia)': {numeric: 203, alpha3: 'CZE', name: 'Czech,Republic'},
    "Côte d'Ivoire": {numeric: 384, alpha3: 'CIV', name: "Côte,d'Ivoire"},
    'Denmark': {numeric: 208, alpha3: 'DNK', name: 'Denmark'},
    'Djibouti': {numeric: 262, alpha3: 'DJI', name: 'Djibouti'},
    'Dominica': {numeric: 212, alpha3: 'DMA', name: 'Dominica'},
    'Dominican Republic': {numeric: 214, alpha3: 'DOM', name: 'Dominican,Republic'},
    'Ecuador': {numeric: 218, alpha3: 'ECU', name: 'Ecuador'},
    'Egypt': {numeric: 818, alpha3: 'EGY', name: 'Egypt'},
    'El Salvador': {numeric: 222, alpha3: 'SLV', name: 'El,Salvador'},
    'Equatorial Guinea': {numeric: 226, alpha3: 'GNQ', name: 'Equatorial,Guinea'},
    'Eritrea': {numeric: 232, alpha3: 'ERI', name: 'Eritrea'},
    'Estonia': {numeric: 233, alpha3: 'EST', name: 'Estonia'},
    'Ethiopia': {numeric: 231, alpha3: 'ETH', name: 'Ethiopia'},
    'Falkland Islands': {numeric: 238, alpha3: 'FLK', name: 'Falkland,Islands,(Malvinas)'},
    'Faeroe Islands': {numeric: 234, alpha3: 'FRO', name: 'Faroe,Islands'},
    'Fiji': {numeric: 242, alpha3: 'FJI', name: 'Fiji'},
    'Finland': {numeric: 246, alpha3: 'FIN', name: 'Finland'},
    'France': {numeric: 250, alpha3: 'FRA', name: 'France'},
    'French Guiana': {numeric: 254, alpha3: 'GUF', name: 'French,Guiana'},
    'French Polynesia': {numeric: 258, alpha3: 'PYF', name: 'French,Polynesia'},
    'French,Southern,Territories': {numeric: 260, alpha3: 'ATF', name: 'French,Southern,Territories'},
    'Gabon': {numeric: 266, alpha3: 'GAB', name: 'Gabon'},
    'Gambia': {numeric: 270, alpha3: 'GMB', name: 'Gambia'},
    'Georgia': {numeric: 268, alpha3: 'GEO', name: 'Georgia'},
    'Germany': {numeric: 276, alpha3: 'DEU', name: 'Germany'},
    'Ghana': {numeric: 288, alpha3: 'GHA', name: 'Ghana'},
    'Gibraltar': {numeric: 292, alpha3: 'GIB', name: 'Gibraltar'},
    'Greece': {numeric: 300, alpha3: 'GRC', name: 'Greece'},
    'Greenland': {numeric: 304, alpha3: 'GRL', name: 'Greenland'},
    'Grenada': {numeric: 308, alpha3: 'GRD', name: 'Grenada'},
    'Guadeloupe': {numeric: 312, alpha3: 'GLP', name: 'Guadeloupe'},
    'Guam': {numeric: 316, alpha3: 'GUM', name: 'Guam'},
    'Guatemala': {numeric: 320, alpha3: 'GTM', name: 'Guatemala'},
    'Channel Islands': {numeric: 831, alpha3: 'GGY', name: 'Guernsey'},
    'Guinea': {numeric: 324, alpha3: 'GIN', name: 'Guinea'},
    'Guinea-Bissau': {numeric: 624, alpha3: 'GNB', name: 'Guinea-Bissau'},
    'Guyana': {numeric: 328, alpha3: 'GUY', name: 'Guyana'},
    'Haiti': {numeric: 332, alpha3: 'HTI', name: 'Haiti'},
    'Heard,Island,and,McDonald,Islands': {numeric: 334, alpha3: 'HMD', name: 'Heard,Island,and,McDonald,Islands'},
    'Holy,See,(Vatican,City,State)': {numeric: 336, alpha3: 'VAT', name: 'Holy,See,(Vatican,City,State)'},
    'Honduras': {numeric: 340, alpha3: 'HND', name: 'Honduras'},
    'Hong Kong': {numeric: 344, alpha3: 'HKG', name: 'Hong,Kong'},
    'Hungary': {numeric: 348, alpha3: 'HUN', name: 'Hungary'},
    'Iceland': {numeric: 352, alpha3: 'ISL', name: 'Iceland'},
    'India': {numeric: 356, alpha3: 'IND', name: 'India'},
    'Indonesia': {numeric: 360, alpha3: 'IDN', name: 'Indonesia'},
    'Iran': {numeric: 364, alpha3: 'IRN', name: 'Iran,,Islamic,Republic,of'},
    'Iraq': {numeric: 368, alpha3: 'IRQ', name: 'Iraq'},
    'Ireland': {numeric: 372, alpha3: 'IRL', name: 'Ireland'},
    'Isle of Man': {numeric: 833, alpha3: 'IMN', name: 'Isle,of,Man'},
    'Israel': {numeric: 376, alpha3: 'ISR', name: 'Israel'},
    'Italy': {numeric: 380, alpha3: 'ITA', name: 'Italy'},
    'Jamaica': {numeric: 388, alpha3: 'JAM', name: 'Jamaica'},
    'Japan': {numeric: 392, alpha3: 'JPN', name: 'Japan'},
    'Jersey': {numeric: 832, alpha3: 'JEY', name: 'Jersey'},
    'Jordan': {numeric: 400, alpha3: 'JOR', name: 'Jordan'},
    'Kazakhstan': {numeric: 398, alpha3: 'KAZ', name: 'Kazakhstan'},
    'Kenya': {numeric: 404, alpha3: 'KEN', name: 'Kenya'},
    'Kiribati': {numeric: 296, alpha3: 'KIR', name: 'Kiribati'},
    "North Korea": {numeric: 408, alpha3: 'PRK', name: "Korea,,Democratic,People's,Republic,of"},
    'South Korea': {numeric: 410, alpha3: 'KOR', name: 'Korea,,Republic,of'},
    'Kuwait': {numeric: 414, alpha3: 'KWT', name: 'Kuwait'},
    'Kyrgyzstan': {numeric: 417, alpha3: 'KGZ', name: 'Kyrgyzstan'},
    "Laos": {numeric: 418, alpha3: 'LAO', name: "Lao,People's,Democratic,Republic"},
    'Latvia': {numeric: 428, alpha3: 'LVA', name: 'Latvia'},
    'Lebanon': {numeric: 422, alpha3: 'LBN', name: 'Lebanon'},
    'Lesotho': {numeric: 426, alpha3: 'LSO', name: 'Lesotho'},
    'Liberia': {numeric: 430, alpha3: 'LBR', name: 'Liberia'},
    'Libya': {numeric: 434, alpha3: 'LBY', name: 'Libya'},
    'Liechtenstein': {numeric: 438, alpha3: 'LIE', name: 'Liechtenstein'},
    'Lithuania': {numeric: 440, alpha3: 'LTU', name: 'Lithuania'},
    'Luxembourg': {numeric: 442, alpha3: 'LUX', name: 'Luxembourg'},
    'Macao': {numeric: 446, alpha3: 'MAC', name: 'Macao'},
    'North Macedonia': {numeric: 807, alpha3: 'MKD', name: 'Macedonia,,the,Former,Yugoslav,Republic,of'},
    'Madagascar': {numeric: 450, alpha3: 'MDG', name: 'Madagascar'},
    'Malawi': {numeric: 454, alpha3: 'MWI', name: 'Malawi'},
    'Malaysia': {numeric: 458, alpha3: 'MYS', name: 'Malaysia'},
    'Maldives': {numeric: 462, alpha3: 'MDV', name: 'Maldives'},
    'Mali': {numeric: 466, alpha3: 'MLI', name: 'Mali'},
    'Malta': {numeric: 470, alpha3: 'MLT', name: 'Malta'},
    'Marshall Islands': {numeric: 584, alpha3: 'MHL', name: 'Marshall,Islands'},
    'Martinique': {numeric: 474, alpha3: 'MTQ', name: 'Martinique'},
    'Mauritania': {numeric: 478, alpha3: 'MRT', name: 'Mauritania'},
    'Mauritius': {numeric: 480, alpha3: 'MUS', name: 'Mauritius'},
    'Mayotte': {numeric: 175, alpha3: 'MYT', name: 'Mayotte'},
    'Mexico': {numeric: 484, alpha3: 'MEX', name: 'Mexico'},
    'Micronesia': {numeric: 583, alpha3: 'FSM', name: 'Micronesia,,Federated,States,of'},
    'Moldova': {numeric: 498, alpha3: 'MDA', name: 'Moldova,,Republic,of'},
    'Monaco': {numeric: 492, alpha3: 'MCO', name: 'Monaco'},
    'Mongolia': {numeric: 496, alpha3: 'MNG', name: 'Mongolia'},
    'Montenegro': {numeric: 499, alpha3: 'MNE', name: 'Montenegro'},
    'Montserrat': {numeric: 500, alpha3: 'MSR', name: 'Montserrat'},
    'Morocco': {numeric: 504, alpha3: 'MAR', name: 'Morocco'},
    'Mozambique': {numeric: 508, alpha3: 'MOZ', name: 'Mozambique'},
    'Myanmar': {numeric: 104, alpha3: 'MMR', name: 'Myanmar'},
    'Namibia': {numeric: 516, alpha3: 'NAM', name: 'Namibia'},
    'Nauru': {numeric: 520, alpha3: 'NRU', name: 'Nauru'},
    'Nepal': {numeric: 524, alpha3: 'NPL', name: 'Nepal'},
    'Netherlands': {numeric: 528, alpha3: 'NLD', name: 'Netherlands'},
    'New Caledonia': {numeric: 540, alpha3: 'NCL', name: 'New,Caledonia'},
    'New Zealand': {numeric: 554, alpha3: 'NZL', name: 'New,Zealand'},
    'Nicaragua': {numeric: 558, alpha3: 'NIC', name: 'Nicaragua'},
    'Niger': {numeric: 562, alpha3: 'NER', name: 'Niger'},
    'Nigeria': {numeric: 566, alpha3: 'NGA', name: 'Nigeria'},
    'Niue': {numeric: 570, alpha3: 'NIU', name: 'Niue'},
    'Norfolk,Island': {numeric: 574, alpha3: 'NFK', name: 'Norfolk,Island'},
    'Northern Mariana Islands': {numeric: 580, alpha3: 'MNP', name: 'Northern,Mariana,Islands'},
    'Norway': {numeric: 578, alpha3: 'NOR', name: 'Norway'},
    'Oman': {numeric: 512, alpha3: 'OMN', name: 'Oman'},
    'Pakistan': {numeric: 586, alpha3: 'PAK', name: 'Pakistan'},
    'Palau': {numeric: 585, alpha3: 'PLW', name: 'Palau'},
    'State of Palestine': {numeric: 275, alpha3: 'PSE', name: 'Palestine,,State,of'},
    'Panama': {numeric: 591, alpha3: 'PAN', name: 'Panama'},
    'Papua New Guinea': {numeric: 598, alpha3: 'PNG', name: 'Papua,New,Guinea'},
    'Paraguay': {numeric: 600, alpha3: 'PRY', name: 'Paraguay'},
    'Peru': {numeric: 604, alpha3: 'PER', name: 'Peru'},
    'Philippines': {numeric: 608, alpha3: 'PHL', name: 'Philippines'},
    'Pitcairn': {numeric: 612, alpha3: 'PCN', name: 'Pitcairn'},
    'Poland': {numeric: 616, alpha3: 'POL', name: 'Poland'},
    'Portugal': {numeric: 620, alpha3: 'PRT', name: 'Portugal'},
    'Puerto Rico': {numeric: 630, alpha3: 'PRI', name: 'Puerto,Rico'},
    'Qatar': {numeric: 634, alpha3: 'QAT', name: 'Qatar'},
    'Romania': {numeric: 642, alpha3: 'ROU', name: 'Romania'},
    'Russia': {numeric: 643, alpha3: 'RUS', name: 'Russian,Federation'},
    'Rwanda': {numeric: 646, alpha3: 'RWA', name: 'Rwanda'},
    'Réunion': {numeric: 638, alpha3: 'REU', name: 'Réunion'},
    'Saint Barthelemy': {numeric: 652, alpha3: 'BLM', name: 'Saint,Barthélemy'},
    'Saint Helena': {numeric: 654, alpha3: 'SHN', name: 'Saint,Helena,,Ascension,and,Tristan,da,Cunha'},
    'Saint Kitts & Nevis': {numeric: 659, alpha3: 'KNA', name: 'Saint,Kitts,and,Nevis'},
    'Saint Lucia': {numeric: 662, alpha3: 'LCA', name: 'Saint,Lucia'},
    'Saint Martin': {numeric: 663, alpha3: 'MAF', name: 'Saint,Martin,(French,part)'},
    'Saint Pierre & Miquelon': {numeric: 666, alpha3: 'SPM', name: 'Saint,Pierre,and,Miquelon'},
    'St. Vincent & Grenadines': {numeric: 670, alpha3: 'VCT', name: 'Saint,Vincent,and,the,Grenadines'},
    'Samoa': {numeric: 882, alpha3: 'WSM', name: 'Samoa'},
    'San Marino': {numeric: 674, alpha3: 'SMR', name: 'San,Marino'},
    'Sao Tome & Principe': {numeric: 678, alpha3: 'STP', name: 'Sao,Tome,and,Principe'},
    'Saudi Arabia': {numeric: 682, alpha3: 'SAU', name: 'Saudi,Arabia'},
    'Senegal': {numeric: 686, alpha3: 'SEN', name: 'Senegal'},
    'Serbia': {numeric: 688, alpha3: 'SRB', name: 'Serbia'},
    'Seychelles': {numeric: 690, alpha3: 'SYC', name: 'Seychelles'},
    'Sierra Leone': {numeric: 694, alpha3: 'SLE', name: 'Sierra,Leone'},
    'Singapore': {numeric: 702, alpha3: 'SGP', name: 'Singapore'},
    'Sint Maarten': {numeric: 534, alpha3: 'SXM', name: 'Sint,Maarten,(Dutch,part)'},
    'Slovakia': {numeric: 703, alpha3: 'SVK', name: 'Slovakia'},
    'Slovenia': {numeric: 705, alpha3: 'SVN', name: 'Slovenia'},
    'Solomon Islands': {numeric: 90, alpha3: 'SLB', name: 'Solomon,Islands'},
    'Somalia': {numeric: 706, alpha3: 'SOM', name: 'Somalia'},
    'South Africa': {numeric: 710, alpha3: 'ZAF', name: 'South,Africa'},
    'South,Georgia,and,the,South,Sandwich,Islands': {numeric: 239, alpha3: 'SGS', name: 'South,Georgia,and,the,South,Sandwich,Islands'},
    'South Sudan': {numeric: 728, alpha3: 'SSD', name: 'South,Sudan'},
    'Spain': {numeric: 724, alpha3: 'ESP', name: 'Spain'},
    'Sri Lanka': {numeric: 144, alpha3: 'LKA', name: 'Sri,Lanka'},
    'Sudan': {numeric: 729, alpha3: 'SDN', name: 'Sudan'},
    'Suriname': {numeric: 740, alpha3: 'SUR', name: 'Suriname'},
    'Svalbard,and,Jan,Mayen': {numeric: 744, alpha3: 'SJM', name: 'Svalbard,and,Jan,Mayen'},
    'Eswatini': {numeric: 748, alpha3: 'SWZ', name: 'Swaziland'},
    'Sweden': {numeric: 752, alpha3: 'SWE', name: 'Sweden'},
    'Switzerland': {numeric: 756, alpha3: 'CHE', name: 'Switzerland'},
    'Syria': {numeric: 760, alpha3: 'SYR', name: 'Syrian,Arab,Republic'},
    'Taiwan': {numeric: 158, alpha3: 'TWN', name: 'Taiwan,,Province,of,China'},
    'Tajikistan': {numeric: 762, alpha3: 'TJK', name: 'Tajikistan'},
    'Tanzania': {numeric: 834, alpha3: 'TZA', name: 'Tanzania,,United,Republic,of'},
    'Thailand': {numeric: 764, alpha3: 'THA', name: 'Thailand'},
    'Timor-Leste': {numeric: 626, alpha3: 'TLS', name: 'Timor-Leste'},
    'Togo': {numeric: 768, alpha3: 'TGO', name: 'Togo'},
    'Tokelau': {numeric: 772, alpha3: 'TKL', name: 'Tokelau'},
    'Tonga': {numeric: 776, alpha3: 'TON', name: 'Tonga'},
    'Trinidad and Tobago': {numeric: 780, alpha3: 'TTO', name: 'Trinidad,and,Tobago'},
    'Tunisia': {numeric: 788, alpha3: 'TUN', name: 'Tunisia'},
    'Turkey': {numeric: 792, alpha3: 'TUR', name: 'Turkey'},
    'Turkmenistan': {numeric: 795, alpha3: 'TKM', name: 'Turkmenistan'},
    'Turks and Caicos': {numeric: 796, alpha3: 'TCA', name: 'Turks,and,Caicos,Islands'},
    'Tuvalu': {numeric: 798, alpha3: 'TUV', name: 'Tuvalu'},
    'Uganda': {numeric: 800, alpha3: 'UGA', name: 'Uganda'},
    'Ukraine': {numeric: 804, alpha3: 'UKR', name: 'Ukraine'},
    'United Arab Emirates': {numeric: 784, alpha3: 'ARE', name: 'United,Arab,Emirates'},
    'United Kingdom': {numeric: 826, alpha3: 'GBR', name: 'United,Kingdom'},
    'United States': {numeric: 840, alpha3: 'USA', name: 'United,States'},
    'United,States,Minor,Outlying,Islands': {numeric: 581, alpha3: 'UMI', name: 'United,States,Minor,Outlying,Islands'},
    'Uruguay': {numeric: 858, alpha3: 'URY', name: 'Uruguay'},
    'Uzbekistan': {numeric: 860, alpha3: 'UZB', name: 'Uzbekistan'},
    'Vanuatu': {numeric: 548, alpha3: 'VUT', name: 'Vanuatu'},
    'Venezuela': {numeric: 862, alpha3: 'VEN', name: 'Venezuela,,Bolivarian,Republic,of'},
    'Vietnam': {numeric: 704, alpha3: 'VNM', name: 'Viet,Nam'},
    'British Virgin Islands': {numeric: 92, alpha3: 'VGB', name: 'Virgin,Islands,,British'},
    'U.S. Virgin Islands': {numeric: 850, alpha3: 'VIR', name: 'Virgin,Islands,,U.S.'},
    'Wallis & Futuna': {numeric: 876, alpha3: 'WLF', name: 'Wallis,and,Futuna'},
    'Western Sahara': {numeric: 732, alpha3: 'ESH', name: 'Western,Sahara'},
    'Yemen': {numeric: 887, alpha3: 'YEM', name: 'Yemen'},
    'Zambia': {numeric: 894, alpha3: 'ZMB', name: 'Zambia'},
    'Zimbabwe': {numeric: 716, alpha3: 'ZWE', name: 'Zimbabwe'},
    'Åland,Islands': {numeric: 248, alpha3: 'ALA', name: 'Åland,Islands'},
}